[jira]
api_url = "https://your-jira-instance.atlassian.net/rest/api/3"
username = "your-jira-username"
password = "your-jira-password"
# projects_filter = ["PROJECTFOO", "PROJECTBAR"]  # Optional: Only process tickets from these projects
# comment_visibility = "role:Member" # Optional: set comment visibility to certain values
                                   # Use $TICKETID or #TICKETID format in commits to force public visibility

[gitea]
webhook_secret = "your-webhook-secret"  # Optional

[ssl]
cert_file = "/path/to/cert.pem"
key_file = "/path/to/key.pem"

[server]
port = "8443"
# allowed_cidrs = ["192.168.1.0/24", "10.0.0.0/8", "172.16.0.0/12"]  # Optional: restrict POST requests to specific IP ranges

[buffering]
duration = "10m"   # Optional: buffer duration (e.g., "5s", "10m", "1h") - if set, buffering is enabled
